name: Enforce PR Source Branch

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write   # Needed to comment and close PRs

jobs:
  check-source:
    runs-on: ubuntu-latest
    steps:
      - name: Check and act on PR source branch
        run: |
          echo "🔍 Checking source branch for PR #${{ github.event.pull_request.number }}..."
          if [[ "${{ github.head_ref }}" != "staging" ]]; then
            echo "❌ Invalid source branch: '${{ github.head_ref }}'"
            
            # Add a comment explaining the closure
            gh pr comment ${{ github.event.pull_request.number }} \
              --body "⚠️ This PR was automatically closed because PRs to **main** must come from **staging**. Please update your branch and try again."

            # Close the PR
            gh pr close ${{ github.event.pull_request.number }}

            exit 1
          else
            echo "✅ Source branch is staging. PR is allowed."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
